# Generated by Django 5.0.7 on 2024-08-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=255, verbose_name='Email'),
        ),
    ]
